---

- name: "Install aptitude"
  apt:
    name:
      - aptitude
    cache_valid_time: 300
    state: present
  become: yes

- name: "Run apt update"
  apt:
    upgrade: full
    cache_valid_time: 300
  become: yes

- name: "Run apt autoremove"
  apt:
    autoremove: yes
    cache_valid_time: 300
  become: yes

- name: "Run apt autoclean"
  apt:
    autoclean: yes
    cache_valid_time: 300
  become: yes

- name: "Reboot if required"
  block:
    - name: "Run pre-reboot check commands"
      shell: "{{ command }}" # noqa 305
      loop: "{{ pre_reboot_checks | default(default_pre_reboot_checks) }}"
      register: check_output
      changed_when: false
      loop_control:
        loop_var: command
    - name: "Check if restarting is required"
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: "Reboot"
      reboot:
      when: reboot_required.stat.exists
  when: automatic_reboot_enabled
  become: yes
