---

- name: "Upgrade all packages"
  yum:
    name: "*"
    state: latest # noqa 403
  become: yes

- name: "Reboot if required"
  block:
    - name: "Run pre-reboot check commands"
      shell: "{{ command }}" # noqa 305
      loop: "{{ pre_reboot_checks | default(default_pre_reboot_checks) }}"
      register: check_output
      changed_when: false
      loop_control:
        loop_var: command

    - name: "Check if restarting is required"
      shell: "needs-restarting -r" # noqa 305
      register: reboot_required
      failed_when: false
      changed_when: false

    - name: "Reboot"
      reboot:
      when: reboot_required.rc == 1
  when: automatic_reboot_enabled
  become: yes
